language: scala
sudo: false

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

install: /bin/true

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test doc
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
