version: '3'

services:
  dev:
    build:
      context: .
    volumes:
      - .:/app:cached
    environment:
      - SBT_OPTS=-Xms512M -Xmx2G -Xss2M -XX:MaxMetaspaceSize=1024M -XX:+CMSClassUnloadingEnabled
